#### Numpy

- Pandas : https://pandas.pydata.org/
- Numpy : https://numpy.org/

- 수치해석, 수학적 처리, 통계 등을 위한 라이브러리(모듈) - Scipy, Pandas, Matplotlib

##### Numpy 설치
```python
!pip install numpy
```


In [1]:
# 현재 버전 확인
!pip list

Package           Version
----------------- -------
asttokens         2.2.1
backcall          0.2.0
colorama          0.4.6
comm              0.1.3
contourpy         1.1.0
cycler            0.11.0
debugpy           1.6.7
decorator         5.1.1
et-xmlfile        1.1.0
executing         1.2.0
Faker             18.11.1
fonttools         4.40.0
ipykernel         6.23.2
ipython           8.14.0
jedi              0.18.2
Jinja2            3.1.2
jupyter_client    8.2.0
jupyter_core      5.3.1
kiwisolver        1.4.4
MarkupSafe        2.1.3
matplotlib        3.7.1
matplotlib-inline 0.1.6
nest-asyncio      1.5.6
numpy             1.25.0
openpyxl          3.1.2
packaging         23.1
pandas            2.0.2
parso             0.8.3
pickleshare       0.7.5
Pillow            9.5.0
pip               23.1.2
platformdirs      3.7.0
prompt-toolkit    3.0.38
psutil            5.9.5
pure-eval         0.2.2
Pygments          2.15.1
PyMySQL           1.0.3
pyparsing         3.1.0
python-dateutil   2.8.2
py

In [2]:
!pip install numpy

In [3]:
!pip install pandas

In [4]:
# import
import pandas as pd 
import numpy as np


##### numpy를 쓰는 이유
- python 리스트를 만들고 사용처리(100만건) - 대략 200ms
- numpy 배열을 만들고 사용처리(100만건) - 대략 20ms (10배정도 빠름) 

In [6]:
py_list = list(range(1_000_000)) # 100만건 리스트 만들기

In [7]:
np_arr = np.arange(1_000_000)

In [8]:
## 파이썬 리스트 사용
%timeit for _ in range(10): py_list2 = py_list * 2

148 ms ± 2.03 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [9]:
## numpy 배열 사용
%timeit for _ in range(10): np_arr2 = np_arr * 2

13.1 ms ± 112 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


##### 넘파이로 배열 생성, 연산 등

In [10]:
# 생성
np_arr1 = np.array([1, 3, 5])
np_arr1

array([1, 3, 5])

In [14]:
np_arr2 = np.array([[1, 3, 5], [5, 9, 12]])
np_arr2

array([[ 1,  3,  5],
       [ 5,  9, 12]])

In [18]:
np_arr3 = np.array([[[0,2,4], [8,10,12]],[[1,3,5],[7,9,12]]])
np_arr3

array([[[ 0,  2,  4],
        [ 8, 10, 12]],

       [[ 1,  3,  5],
        [ 7,  9, 12]]])

In [19]:
list1 = [1, 3, 5]
list1

[1, 3, 5]

In [20]:
list2 = [[1,3,5], [1,3,5]]
list2

[[1, 3, 5], [1, 3, 5]]

In [23]:
# 길의 4의 1차원 배열을 전부 0으로 채울것
np_arr4 = np.zeros(4)
np_arr4

array([0., 0., 0., 0.])

In [22]:
np_arr5 = np.zeros([2,3])
np_arr5

array([[0., 0., 0.],
       [0., 0., 0.]])

In [24]:
np_arr6 = np.empty((2,3,1))
np_arr6

array([[[0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.]]])

In [26]:
# 랜덤은 활용도 있음
np.random.randn(2,3)


array([[ 0.49655198, -0.78844915, -0.39726545],
       [-0.32624392,  1.0619478 , -0.6882609 ]])

In [31]:
np_arr7 = np.arange(10)
np_arr7

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
# 파이썬에서 리스트만든 다음에 numpy형태의 배열로 변경
np.array(list(range(10)))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
# 연산
np_arr7 + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [34]:
np_arr7 * 3

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [35]:
np_arr7 / 4

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25])

In [36]:
np_arr7 // 2

array([0, 0, 1, 1, 2, 2, 3, 3, 4, 4], dtype=int32)

In [37]:
np_arr7 + np_arr7

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [38]:
# 비교 연산
(np_arr7 + np_arr7) < 9

array([ True,  True,  True,  True,  True, False, False, False, False,
       False])

In [41]:
(np_arr7 + np_arr7) != 10

array([ True,  True,  True,  True,  True, False,  True,  True,  True,
        True])

In [43]:
# numpy 배열은 +는 더하기 연산
# 파이썬 리스트 +는 concat(두 리스트를 합침) 
list(np_arr7) + list(np_arr7)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [44]:
# 조회
np_arr7[1]

1

In [46]:
# 인덱스 크기를 벗어나면 IndexError 예외발생
np_arr7[10]

IndexError: index 10 is out of bounds for axis 0 with size 10

In [47]:
np_arr7[np_arr7 < 5]

array([0, 1, 2, 3, 4])

In [57]:
list2 = list(range(10))
[x for x in range(len(list2)) if x < 5]

[0, 1, 2, 3, 4]

In [59]:
np_arr7[3:9] # 뒤에 인덱스는 항상 -1

array([3, 4, 5, 6, 7, 8])

In [72]:
# 2차원 배열에서 값 조회
np_arr2[1][2]

12

In [73]:
np_arr2[1][2] = 9
np_arr2

array([[1, 3, 5],
       [5, 9, 9]])

In [71]:
# 값 변경(치환)
np_arr7[np_arr7 < 5] = 100
np_arr7

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9])

##### 속성
- shape, dtype, T

In [77]:
# 1차원
np_arr1.shape

(3,)

In [78]:
# 2차원
np_arr2.shape

(2, 3)

In [81]:
# 값의 타입
np_arr2.dtype

dtype('int32')

In [85]:
# Pivot
np_arr2.T

array([[1, 5],
       [3, 9],
       [5, 9]])

In [84]:
np_arr2.T.shape

(3, 2)

#### 기타함수

In [86]:
np_arr8 = np.arange(10)
np_arr8

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [88]:
np_arr8.mean()

4.5

In [89]:
np_arr8.sum()

45

In [90]:
np_arr8.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45])

In [92]:
np_arr9 = np.random.randn(10)
np_arr9

array([-1.57813676,  0.34163829, -1.82734021,  1.21763687,  1.29332114,
        0.76320845,  1.55385533,  0.09711857, -0.19841874,  0.84334614])

In [97]:
# 오름차순 정렬
np_arr9.sort()

In [95]:
np_arr9

array([-1.82734021, -1.57813676, -0.19841874,  0.09711857,  0.34163829,
        0.76320845,  0.84334614,  1.21763687,  1.29332114,  1.55385533])

In [98]:
# 내림차순 정렬
-np.sort(-np_arr9)

array([ 1.55385533,  1.29332114,  1.21763687,  0.84334614,  0.76320845,
        0.34163829,  0.09711857, -0.19841874, -1.57813676, -1.82734021])

#### 테스트용 데이터프레임 예제

In [115]:
# 테스트용 더미데이터프레임 만들기
# 판다스와 조합해서 생성
size = 10
df = pd.DataFrame({
    'class': [['A', 'B', 'C', 'D', 'F'][np.random.randint(0, 5)] for i in range(0, size)],
    'year': [np.random.randint(2010, 2024) for i in range(0, size)],
    'month': [np.random.randint(1, 13) for i in range(0, size)],
    'val1': [np.random.randint(1,11) for i in range(0,size)],
    'val2': [np.random.randint(100,1000) for i in range(0,size)],
    'val3': [np.random.randint(10000,20000) for i in range(0,size)]
})

df

class  year  month  val1  val2   val3
0     F  2020      9     2   513  13020
1     A  2020      4     4   164  17748
2     C  2022      7     6   359  14278
3     A  2021      2     6   942  17398
4     D  2015      9     3   393  16868
5     F  2012      6     7   670  11899
6     B  2022      5     1   187  17010
7     B  2018      3     4   250  15453
8     A  2014      8    10   626  13251
9     F  2018      6     8   953  19478

In [116]:
df.shape

(10, 6)

In [117]:
df.dtypes

class    object
year      int64
month     int64
val1      int64
val2      int64
val3      int64
dtype: object

In [120]:
df.T

0      1      2      3      4      5      6      7      8      9
class      F      A      C      A      D      F      B      B      A      F
year    2020   2020   2022   2021   2015   2012   2022   2018   2014   2018
month      9      4      7      2      9      6      5      3      8      6
val1       2      4      6      6      3      7      1      4     10      8
val2     513    164    359    942    393    670    187    250    626    953
val3   13020  17748  14278  17398  16868  11899  17010  15453  13251  19478